// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq1xAFMcGWQ_dkIak5lmi6kPBdKDv8xqc',
    appId: '1:865328214254:web:c5b5015a100e4b4cc543ff',
    messagingSenderId: '865328214254',
    projectId: 'grocerygo-d297f',
    authDomain: 'grocerygo-d297f.firebaseapp.com',
    storageBucket: 'grocerygo-d297f.firebasestorage.app',
    measurementId: 'G-3L77Z2Q0S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADyk2GDf35eybuJ_8rjWlkTfwkqjMxLnY',
    appId: '1:865328214254:android:d0367003450c554cc543ff',
    messagingSenderId: '865328214254',
    projectId: 'grocerygo-d297f',
    storageBucket: 'grocerygo-d297f.firebasestorage.app',
  );

}